import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import {mkdtemp,readFile,stat,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';import {join} from 'node:path';import {scryptSync} from 'node:crypto';
import {createApp} from '../server.js';
import {UserStore} from '../lib/admin.js';
const adminPassword='correct horse battery staple',salt='test-salt',hash=scryptSync(adminPassword,salt,32).toString('hex');
async function fixture(extra={}){const stateDir=extra.stateDir||await mkdtemp(join(tmpdir(),'mcp-admin-'));const app=await createApp({stateDir,adminEmail:'admin@example.com',adminPasswordSalt:salt,adminPasswordHash:hash,...extra});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${app.server.address().port}`;return {app,stateDir,request:(p,o={})=>fetch(base+p,o)}}
const json=(method,body,headers={})=>({method,headers:{'content-type':'application/json',...headers},body:JSON.stringify(body)}),bearer=t=>({authorization:`Bearer ${t}`});
async function adminLogin(f){return (await (await f.request('/admin/login',json('POST',{email:'admin@example.com',password:adminPassword}))).json()).token}
async function create(f,token,email='user@example.com',extra={}){const r=await f.request('/admin/users',json('POST',{email,...extra},bearer(token)));return {status:r.status,...await r.json()}}
async function userLogin(f,email,password){return f.request('/auth/login',json('POST',{email,credential:password}))}

test('admin auth bearer remains supported, generic, expiring and revocable',async t=>{let now=1000;const f=await fixture({now:()=>now,adminSessionTtlMs:100});t.after(()=>f.app.close());for(const body of [{email:'x@y.com',password:adminPassword},{email:'admin@example.com',password:'wrong'}])assert.equal((await f.request('/admin/login',json('POST',body))).status,401);const token=await adminLogin(f);assert.equal((await f.request('/admin/users',{headers:bearer(token)})).status,200);now+=101;assert.equal((await f.request('/admin/users',{headers:bearer(token)})).status,401)});

test('create returns a strong password once, no API key, stores verifier only, and upsert preserves password',async t=>{const f=await fixture();t.after(()=>f.app.close());const token=await adminLogin(f),first=await create(f,token,' Alice@Example.COM ',{label:'Alice'});assert.equal(first.status,201);assert.ok(first.password.length>=16);assert.equal(first.key,undefined);assert.equal(first.user.keyId,null);const disk=await readFile(join(f.stateDir,'users.json'),'utf8');assert.equal(disk.includes(first.password),false);assert.match(disk,/passwordHash/);assert.equal((await stat(join(f.stateDir,'users.json'))).mode&0o777,0o600);const again=await create(f,token,'alice@example.com',{label:'A2'});assert.equal(again.status,200);assert.equal(again.password,undefined);assert.equal(again.user.id,first.user.id);const listed=await (await f.request('/admin/users',{headers:bearer(token)})).json();assert.equal(JSON.stringify(listed).includes('passwordHash'),false)});

test('password login, profile, session limits, API-key rejection and password rotation',async t=>{const f=await fixture();t.after(()=>f.app.close());const admin=await adminLogin(f),made=await create(f,admin,'user@example.com',{maxSessions:2});let r=await userLogin(f,' USER@example.com ',made.password);assert.equal(r.status,200);const cookie1=r.headers.get('set-cookie');r=await userLogin(f,'user@example.com',made.password);const cookie2=r.headers.get('set-cookie');r=await f.request('/profile',{headers:{cookie:cookie1}});const profile=await r.json();assert.equal(profile.role,'user');assert.equal(profile.hasApiKey,false);assert.equal(JSON.stringify(profile).includes('password'),false);r=await f.request('/profile/password',json('POST',{currentPassword:made.password,newPassword:'a sufficiently new password',confirmPassword:'a sufficiently new password'},{cookie:cookie1}));assert.equal(r.status,200);const replacement=r.headers.get('set-cookie');assert.equal((await f.request('/auth/session',{headers:{cookie:cookie1}})).status,401);assert.equal((await f.request('/auth/session',{headers:{cookie:cookie2}})).status,401);assert.equal((await f.request('/auth/session',{headers:{cookie:replacement}})).status,200);assert.equal((await userLogin(f,'user@example.com',made.password)).status,401);assert.equal((await userLogin(f,'user@example.com','a sufficiently new password')).status,200)});

test('self-service API key create/replace/delete does not invalidate dashboard session',async t=>{const f=await fixture();t.after(()=>f.app.close());const admin=await adminLogin(f),made=await create(f,admin);const login=await userLogin(f,'user@example.com',made.password),cookie=login.headers.get('set-cookie'),mcp=k=>f.request('/mcp',{method:'POST',headers:{authorization:`Bearer ${k}`},body:'{"jsonrpc":"2.0","id":1,"method":"ping"}'});let r=await f.request('/profile/api-key',{method:'POST',headers:{cookie}}),one=await r.json();assert.match(one.key,/^cosmic-mcp-/);assert.equal((await mcp(one.key)).status,200);r=await f.request('/profile/api-key',{method:'POST',headers:{cookie}});const two=await r.json();assert.equal((await mcp(one.key)).status,401);assert.equal((await mcp(two.key)).status,200);assert.equal((await f.request('/auth/session',{headers:{cookie}})).status,200);assert.equal((await f.request('/profile/api-key',{method:'DELETE',headers:{cookie}})).status,204);assert.equal((await mcp(two.key)).status,401)});

test('admin reset/revoke/hard-delete and recreate lifecycle',async t=>{const f=await fixture();t.after(()=>f.app.close());const admin=await adminLogin(f),made=await create(f,admin),login=await userLogin(f,'user@example.com',made.password),cookie=login.headers.get('set-cookie');let r=await f.request('/profile/api-key',{method:'POST',headers:{cookie}}),key=(await r.json()).key;r=await f.request(`/admin/users/${made.user.id}/reset-password`,{method:'POST',headers:bearer(admin)});const reset=await r.json();assert.ok(reset.password.length>=16);assert.equal((await f.request('/auth/session',{headers:{cookie}})).status,401);const relogin=await userLogin(f,'user@example.com',reset.password),newCookie=relogin.headers.get('set-cookie');assert.equal((await f.request(`/admin/users/${made.user.id}/api-key`,{method:'DELETE',headers:bearer(admin)})).status,204);assert.equal((await f.request('/mcp',{method:'POST',headers:{authorization:`Bearer ${key}`},body:'{}'})).status,401);assert.equal((await f.request(`/admin/users/${made.user.id}`,{method:'DELETE',headers:bearer(admin)})).status,204);assert.equal((await f.request('/auth/session',{headers:{cookie:newCookie}})).status,401);assert.equal((await create(f,admin,'user@example.com')).status,201)});

test('legacy passwordless user cannot dashboard login while its MCP key remains valid',async t=>{const dir=await mkdtemp(join(tmpdir(),'legacy-')),stamp=new Date().toISOString(),id='11111111-1111-4111-8111-111111111111';await writeFile(join(dir,'users.json'),JSON.stringify([{id,email:'legacy@example.com',label:'',active:true,expiresAt:null,maxSessions:1,keyId:null,createdAt:stamp,updatedAt:stamp}]));const f=await fixture({stateDir:dir});t.after(()=>f.app.close());const made=await f.app.keys.create('legacy',{userId:id,email:'legacy@example.com'});await f.app.users.update(id,{keyId:made.id});assert.equal((await userLogin(f,'legacy@example.com',made.key)).status,401);const mcp=await f.request('/mcp',{method:'POST',headers:{authorization:`Bearer ${made.key}`},body:'{"jsonrpc":"2.0","id":1,"method":"ping"}'});assert.equal(mcp.status,200);assert.equal(mcp.headers.get('x-ratelimit-limit'),'60')});

test('profile admin is readable but password mutation forbidden; invalid inputs rejected',async t=>{const f=await fixture();t.after(()=>f.app.close());let r=await f.request('/auth/login',json('POST',{email:'admin@example.com',credential:adminPassword})),cookie=r.headers.get('set-cookie');assert.equal((await f.request('/profile',{headers:{cookie}})).status,200);assert.equal((await f.request('/profile/password',json('POST',{currentPassword:'x',newPassword:'long-enough-password'},{cookie}))).status,403);const token=await adminLogin(f);assert.equal((await f.request('/admin/users',json('POST',{email:'bad'},bearer(token)))).status,400);assert.equal((await f.request('/admin/users/..%2Fkeys',{method:'DELETE',headers:bearer(token)})).status,404)});

test('profile password requires confirmation and exact bounded payload',async t=>{const f=await fixture();t.after(()=>f.app.close());const a=await adminLogin(f),made=await create(f,a),login=await userLogin(f,'user@example.com',made.password),cookie=login.headers.get('set-cookie');for(const body of [{currentPassword:made.password,newPassword:'0123456789'},{currentPassword:made.password,newPassword:'0123456789',confirmPassword:'different'},{currentPassword:made.password,newPassword:'123456789',confirmPassword:'123456789'},{currentPassword:made.password,newPassword:'x'.repeat(1025),confirmPassword:'x'.repeat(1025)},{currentPassword:made.password,newPassword:'0123456789',confirmPassword:'0123456789',extra:true}])assert.equal((await f.request('/profile/password',json('POST',body,{cookie}))).status,400);assert.equal((await f.request('/profile/password',json('POST',{currentPassword:made.password,newPassword:'0123456789',confirmPassword:'0123456789'},{cookie}))).status,200)});

test('profile reports remaining expiry and mutations are rate limited',async t=>{let now=1000;const f=await fixture({now:()=>now,profileRateLimit:1});t.after(()=>f.app.close());const a=await adminLogin(f),made=await create(f,a,'user@example.com',{expiresAt:new Date(now+4321).toISOString()}),login=await userLogin(f,'user@example.com',made.password),cookie=login.headers.get('set-cookie');const profile=await (await f.request('/profile',{headers:{cookie}})).json();assert.equal(profile.remainingMs,4321);assert.equal((await f.request('/profile/api-key',{method:'POST',headers:{cookie}})).status,201);assert.equal((await f.request('/profile/api-key',{method:'POST',headers:{cookie}})).status,429);assert.equal((await f.request('/profile',{headers:{cookie}})).status,200)});

test('key replacement rolls back both stores on persistence failures',async t=>{const f=await fixture();t.after(()=>f.app.close());const a=await adminLogin(f),made=await create(f,a),login=await userLogin(f,'user@example.com',made.password),cookie=login.headers.get('set-cookie'),call=()=>f.request('/profile/api-key',{method:'POST',headers:{cookie}});let old=await (await call()).json(),user=f.app.users.get(made.user.id);const save=f.app.keys.save.bind(f.app.keys);f.app.keys.save=async()=>{throw new Error('injected')};assert.equal((await call()).status,500);f.app.keys.save=save;assert.equal(user.keyId,old.keyId);assert.ok(await f.app.keys.authenticate(old.key));const update=f.app.users.commitKey.bind(f.app.users);f.app.users.commitKey=async()=>{throw new Error('injected')};assert.equal((await call()).status,500);f.app.users.commitKey=update;assert.equal(user.keyId,old.keyId);assert.ok(await f.app.keys.authenticate(old.key));assert.equal(f.app.keys.records.filter(k=>k.active&&k.userId===user.id).length,1)});

test('key replacement compensates when user commit persists and then throws',async t=>{const f=await fixture();t.after(()=>f.app.close());const a=await adminLogin(f),made=await create(f,a),login=await userLogin(f,'user@example.com',made.password),cookie=login.headers.get('set-cookie'),call=()=>f.request('/profile/api-key',{method:'POST',headers:{cookie}});const old=await (await call()).json(),user=f.app.users.get(made.user.id),commit=f.app.users.commitKey.bind(f.app.users);f.app.users.commitKey=async(id,keyId)=>{await commit(id,keyId);throw new Error('after persisted commit')};assert.equal((await call()).status,500);const disk=JSON.parse(await readFile(join(f.stateDir,'users.json'),'utf8')).find(u=>u.id===user.id);assert.equal(user.keyId,old.keyId);assert.equal(disk.keyId,old.keyId);assert.equal((await f.app.keys.authenticate(old.key))?.id,old.keyId);assert.equal(f.app.keys.records.filter(k=>k.active&&k.userId===user.id).length,1);assert.equal(f.app.keys.records.some(k=>k.active&&k.id!==old.keyId&&k.userId===user.id),false)});

test('legacy admin emergency rotate remains available',async t=>{const f=await fixture();t.after(()=>f.app.close());const a=await adminLogin(f),made=await create(f,a);const r=await f.request(`/admin/users/${made.user.id}/rotate`,{method:'POST',headers:bearer(a)});assert.equal(r.status,201);const value=await r.json();assert.match(value.key,/^cosmic-mcp-/);assert.equal(value.keyId,f.app.users.get(made.user.id).keyId)});

test('concurrent login enforces one session atomically',async t=>{const f=await fixture();t.after(()=>f.app.close());const a=await adminLogin(f),made=await create(f,a,'race@example.com',{maxSessions:1});const responses=await Promise.all([userLogin(f,'race@example.com',made.password),userLogin(f,'race@example.com',made.password)]);assert.deepEqual(responses.map(r=>r.status).sort(),[200,429]);const cookies=responses.map(r=>r.headers.get('set-cookie')).filter(Boolean);assert.equal(cookies.length,1);assert.equal((await f.request('/auth/session',{headers:{cookie:cookies[0]}})).status,200);assert.equal(f.app.dashboard.sessions.filter(s=>s.userId===made.user.id).length,1)});

test('stalled login body stays outside mutation queue and is closed on deadline',async t=>{const f=await fixture({bodyTimeoutMs:300});t.after(()=>f.app.close());const port=f.app.server.address().port;let responseResolve;const stalledResponse=new Promise(resolve=>responseResolve=resolve),req=http.request({host:'127.0.0.1',port,path:'/auth/login',method:'POST',headers:{'content-type':'application/json','content-length':'100'}},res=>{res.resume();res.on('end',()=>responseResolve(res))});req.on('error',()=>{});req.write('{"email":"never');const started=Date.now(),normal=await f.request('/admin/login',json('POST',{email:'admin@example.com',password:adminPassword}));assert.equal(normal.status,200);assert.ok(Date.now()-started<250,'normal mutation waited for stalled request deadline');const stalled=await stalledResponse;assert.equal(stalled.statusCode,408);assert.equal(stalled.headers.connection,'close');req.destroy()});

test('concurrent key rotations serialize and leave only the second key active',async t=>{const f=await fixture();t.after(()=>f.app.close());const a=await adminLogin(f),made=await create(f,a),login=await userLogin(f,'user@example.com',made.password),cookie=login.headers.get('set-cookie'),mcp=k=>f.request('/mcp',{method:'POST',headers:{authorization:`Bearer ${k}`},body:'{}'});const rs=await Promise.all([f.request('/profile/api-key',{method:'POST',headers:{cookie}}),f.request('/profile/api-key',{method:'POST',headers:{cookie}})]),values=await Promise.all(rs.map(r=>r.json()));assert.equal((await mcp(values[0].key)).status,401);assert.equal((await mcp(values[1].key)).status,200);assert.equal(f.app.users.get(made.user.id).keyId,values[1].keyId);assert.equal(f.app.keys.records.filter(k=>k.userId===made.user.id&&k.active).length,1)});

test('UserStore rolls memory back when update persistence fails',async()=>{let fail=false;const dir=await mkdtemp(join(tmpdir(),'users-rollback-')),store=new UserStore(join(dir,'users.json'),{persist:async(file,value)=>{if(fail)throw new Error('injected');await writeFile(file,JSON.stringify(value))}});await store.load();const made=await store.upsert({email:'rollback@example.com',label:'old'}),old={...made.user};fail=true;await assert.rejects(store.upsert({email:'rollback@example.com',label:'new'}));assert.deepEqual(made.user,old);await assert.rejects(store.update(old.id,{active:false}));assert.deepEqual(made.user,old);await assert.rejects(store.setPassword(old.id,'replacement password'));assert.deepEqual(made.user,old);assert.equal(store.verifyPassword(made.user,made.password),true);assert.equal(store.verifyPassword(made.user,'replacement password'),false)});

test('key deletion compensates key store when user persistence fails',async t=>{const f=await fixture();t.after(()=>f.app.close());const a=await adminLogin(f),made=await create(f,a),login=await userLogin(f,'user@example.com',made.password),cookie=login.headers.get('set-cookie'),created=await (await f.request('/profile/api-key',{method:'POST',headers:{cookie}})).json(),persist=f.app.users.persist;f.app.users.persist=async()=>{throw new Error('injected')};assert.equal((await f.request('/profile/api-key',{method:'DELETE',headers:{cookie}})).status,500);f.app.users.persist=persist;assert.equal(f.app.users.get(made.user.id).keyId,created.keyId);assert.ok(await f.app.keys.authenticate(created.key))});

test('hard delete restores user, key and dashboard session after every persistence phase fails',async t=>{for(const phase of ['key','dashboard','user'])await t.test(phase,async t=>{const f=await fixture();t.after(()=>f.app.close());const a=await adminLogin(f),made=await create(f,a,`${phase}@example.com`),login=await userLogin(f,`${phase}@example.com`,made.password),cookie=login.headers.get('set-cookie'),created=await (await f.request('/profile/api-key',{method:'POST',headers:{cookie}})).json();let restore;if(phase==='key'){restore=f.app.keys.save;let once=true;f.app.keys.save=async function(){if(once){once=false;throw new Error('injected')}return restore.call(this)}}else if(phase==='dashboard'){restore=f.app.dashboard.revokeUser;f.app.dashboard.revokeUser=async()=>{throw new Error('injected')}}else{restore=f.app.users.delete;f.app.users.delete=async()=>{throw new Error('injected')}}assert.equal((await f.request(`/admin/users/${made.user.id}`,{method:'DELETE',headers:bearer(a)})).status,500);if(phase==='key')f.app.keys.save=restore;else if(phase==='dashboard')f.app.dashboard.revokeUser=restore;else f.app.users.delete=restore;assert.ok(f.app.users.get(made.user.id));assert.ok(JSON.parse(await readFile(join(f.stateDir,'users.json'),'utf8')).some(u=>u.id===made.user.id));assert.ok(await f.app.keys.authenticate(created.key));assert.equal((await f.request('/auth/session',{headers:{cookie}})).status,200)})});

test('per-account RPM defaults to 60, validates bounds, and updates an active key immediately',async t=>{let now=1000;const f=await fixture({now:()=>now});t.after(()=>f.app.close());const admin=await adminLogin(f),made=await create(f,admin,'rpm@example.com',{rpmLimit:2});assert.equal(made.user.rpmLimit,2);for(const rpmLimit of [0,601,1.5])assert.equal((await create(f,admin,`bad-${rpmLimit}@example.com`,{rpmLimit})).status,400);const login=await userLogin(f,'rpm@example.com',made.password),cookie=login.headers.get('set-cookie'),created=await (await f.request('/profile/api-key',{method:'POST',headers:{cookie}})).json(),call=()=>f.request('/mcp',{method:'POST',headers:{authorization:`Bearer ${created.key}`},body:'{"jsonrpc":"2.0","id":1,"method":"ping"}'});assert.equal(created.rpmLimit,2);assert.equal((await call()).status,200);assert.equal((await call()).status,200);assert.equal((await call()).status,429);let r=await f.request(`/admin/users/${made.user.id}`,json('PATCH',{rpmLimit:4},bearer(admin)));assert.equal(r.status,200);assert.equal((await r.json()).user.rpmLimit,4);assert.equal((await call()).status,200);assert.equal((await call()).status,429);const defaultUser=await create(f,admin,'default-rpm@example.com');assert.equal(defaultUser.user.rpmLimit,60)});

test('one account runs two parallel API workers, rejects the third, and records successful features',async t=>{const gen=http.createServer(async(req,res)=>{for await(const chunk of req)void chunk;await new Promise(resolve=>setTimeout(resolve,100));res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify({choices:[{message:{content:'ok'}}]}))});await new Promise(resolve=>gen.listen(0,'127.0.0.1',resolve));t.after(()=>new Promise(resolve=>gen.close(resolve)));const f=await fixture({genUrl:`http://127.0.0.1:${gen.address().port}`});t.after(()=>f.app.close());const admin=await adminLogin(f),made=await create(f,admin,'parallel@example.com',{rpmLimit:20}),login=await userLogin(f,'parallel@example.com',made.password),cookie=login.headers.get('set-cookie'),created=await (await f.request('/profile/api-key',{method:'POST',headers:{cookie}})).json(),options={method:'POST',headers:{authorization:`Bearer ${created.key}`,'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'chat_text',arguments:{prompt:'hello'}}})};const responses=await Promise.all([f.request('/mcp',options),f.request('/mcp',options),f.request('/mcp',options)]);assert.deepEqual(responses.map(response=>response.status).sort(),[200,200,429]);const rejected=responses.find(response=>response.status===429);assert.equal((await rejected.json()).workerLimit,2);assert.equal((await f.request('/admin/stats')).status,401);const stats=await (await f.request('/admin/stats',{headers:bearer(admin)})).json();assert.equal(stats.totals.chat,2);assert.equal(stats.totals.overall,2);assert.equal(stats.users.find(user=>user.userId===made.user.id).chat,2)});
