import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { BillingService, PakasirClient, addCalendarMonths } from '../lib/billing.js';
import { UserStore, passwordVerifier } from '../lib/admin.js';
import { createApp } from '../server.js';

test('calendar month extension clamps month-end without losing the time',()=>{
  assert.equal(addCalendarMonths('2024-01-31T12:34:56.789Z').toISOString(),'2024-02-29T12:34:56.789Z');
  assert.equal(addCalendarMonths('2025-01-31T12:34:56.789Z').toISOString(),'2025-02-28T12:34:56.789Z');
});

test('Pakasir client sends the exact contract and rejects mismatched details',async()=>{
  const calls=[],client=new PakasirClient({baseUrl:'https://pakasir.test',projectSlug:'gen',apiKey:'secret',fetchImpl:async(url,options={})=>{calls.push({url:String(url),options});if(String(url).includes('transactioncreate'))return new Response(JSON.stringify({payment:{project:'gen',order_id:'ORDER-1',amount:35000,fee:500,total_payment:35500,payment_method:'qris',payment_number:'000201'}}),{status:200});return new Response(JSON.stringify({transaction:{project:'wrong',order_id:'ORDER-1',amount:35000,status:'completed'}}),{status:200})}});
  const made=await client.create({orderId:'ORDER-1',amount:35000});assert.equal(made.totalPayment,35500);assert.deepEqual(JSON.parse(calls[0].options.body),{project:'gen',order_id:'ORDER-1',amount:35000,api_key:'secret'});await assert.rejects(client.detail({orderId:'ORDER-1',amount:35000}),/tidak cocok/);assert.match(calls[1].url,/project=gen/);assert.match(calls[1].url,/amount=35000/);
});

test('paid orders accumulate exactly once and concurrent create reuses one pending order',async()=>{
  const dir=await mkdtemp(join(tmpdir(),'gen-billing-'));let now=Date.parse('2024-01-15T00:00:00.000Z'),creates=0,details=0;
  const users=new UserStore(join(dir,'users.json'),{now:()=>now});await users.load();const {user}=await users.upsert({email:'paid@example.test',expiresAt:'2024-01-31T12:34:56.789Z'});
  const client={configured:true,create:async({orderId,amount})=>{creates++;await new Promise(resolve=>setTimeout(resolve,10));return{project:'gen',orderId,amount,fee:0,totalPayment:amount,paymentMethod:'qris',paymentNumber:'000201010212',expiredAt:new Date(now+1200000).toISOString()}},detail:async()=>{details++;return{status:'completed',completedAt:new Date(now).toISOString()}}};
  const billing=new BillingService(join(dir,'billing.json'),{users,client,now:()=>now});await billing.load();
  const [first,same]=await Promise.all([billing.create(user),billing.create(user)]);assert.equal(creates,1);assert.equal(first.orderCode,same.orderCode);assert.match(first.qrisDataUrl,/^data:image\/svg\+xml;base64,/);
  const paid=await billing.status(first.orderCode,user.id,{force:true});assert.equal(paid.status,'paid');assert.equal(paid.newExpiresAt,'2024-02-29T12:34:56.789Z');assert.equal(users.get(user.id).accountType,'paid');assert.equal(users.get(user.id).active,true);assert.equal(users.get(user.id).rpmLimit,60);
  const repeat=await billing.status(first.orderCode,user.id,{force:true});assert.equal(repeat.newExpiresAt,paid.newExpiresAt);assert.equal(details,1);
  const second=await billing.create(users.get(user.id));await billing.status(second.orderCode,user.id,{force:true});assert.equal(users.get(user.id).expiresAt,'2024-03-29T12:34:56.789Z');assert.equal(JSON.parse(await readFile(join(dir,'billing.json'),'utf8')).orders.filter(order=>order.status==='paid').length,2);await billing.close();
});

test('expired account extension starts at payment time and order ownership is enforced',async()=>{
  const dir=await mkdtemp(join(tmpdir(),'gen-billing-expired-'));let now=Date.parse('2025-06-10T08:00:00.000Z');const users=new UserStore(join(dir,'users.json'),{now:()=>now});await users.load();const {user}=await users.upsert({email:'expired@example.test',expiresAt:'2025-01-01T00:00:00.000Z'}),other=(await users.upsert({email:'other@example.test',expiresAt:'2025-01-01T00:00:00.000Z'})).user;
  const client={configured:true,create:async({orderId,amount})=>({project:'gen',orderId,amount,fee:0,totalPayment:amount,paymentMethod:'qris',paymentNumber:'000201010212',expiredAt:new Date(now+1200000).toISOString()}),detail:async()=>({status:'completed',completedAt:new Date(now).toISOString()})};const billing=new BillingService(join(dir,'billing.json'),{users,client,now:()=>now});await billing.load();const order=await billing.create(user);await assert.rejects(billing.status(order.orderCode,other.id),error=>error.status===403);const paid=await billing.status(order.orderCode,user.id,{force:true});assert.equal(paid.newExpiresAt,'2025-07-10T08:00:00.000Z');await billing.close();
});

test('public checkout provisions a paid user, emails generated access, and stores no raw credentials',async()=>{
  const dir=await mkdtemp(join(tmpdir(),'gen-public-billing-'));let now=Date.parse('2025-06-10T08:00:00.000Z');const users=new UserStore(join(dir,'users.json'),{now:()=>now});await users.load();const sent=[],credentials={password:'random-paid-password-long'},mailer={sendPaidAccess:async value=>{sent.push(value);return{sent:true}}},client={configured:true,create:async({orderId,amount})=>({project:'gen',orderId,amount,fee:0,totalPayment:amount,paymentMethod:'qris',paymentNumber:'000201010212',expiredAt:new Date(now+1200000).toISOString()}),detail:async()=>({status:'completed',completedAt:new Date(now).toISOString()})},billing=new BillingService(join(dir,'billing.json'),{users,client,mailer,credentialGenerator:()=>credentials,now:()=>now});await billing.load();const made=await billing.createPublic({email:'buyer@example.test',phone:'+628123456789'});assert.equal(made.order.accountAction,'new');await assert.rejects(billing.statusPublic(made.order.orderCode,'wrong'),error=>error.status===401);const paid=await billing.statusPublic(made.order.orderCode,made.checkoutToken,{force:true});assert.equal(paid.order.status,'paid');assert.equal(paid.order.credentialDeliveryStatus,'sent');const user=users.findByEmail('buyer@example.test');assert.equal(paid.userId,user.id);assert.equal(user.phone,'+628123456789');assert.equal(user.accountType,'paid');assert.equal(user.expiresAt,'2025-07-10T08:00:00.000Z');assert.equal(users.verifyPassword(user,credentials.password),true);assert.equal(sent.length,1);assert.equal(sent[0].password,credentials.password);assert.equal('otp' in sent[0],false);const billingDisk=await readFile(join(dir,'billing.json'),'utf8'),userDisk=await readFile(join(dir,'users.json'),'utf8');for(const raw of Object.values(credentials)){assert.equal(billingDisk.includes(raw),false);assert.equal(userDisk.includes(raw),false)}await billing.close();
});

test('failed paid-access email keeps existing credentials and retries without persisting secrets',async()=>{
  const dir=await mkdtemp(join(tmpdir(),'gen-public-retry-'));let now=Date.parse('2025-06-10T08:00:00.000Z'),attempts=0;const users=new UserStore(join(dir,'users.json'),{now:()=>now});await users.load();const oldPassword='existing-password-long',generated={password:'replacement-password-long'},{user}=await users.upsert({email:'retry@example.test',expiresAt:'2025-07-10T08:00:00.000Z'});await users.setPassword(user.id,oldPassword);const mailer={sendPaidAccess:async()=>{attempts++;if(attempts===1)throw new Error('smtp unavailable');return{sent:true}}},client={configured:true,create:async({orderId,amount})=>({project:'gen',orderId,amount,fee:0,totalPayment:amount,paymentMethod:'qris',paymentNumber:'000201010212',expiredAt:new Date(now+1200000).toISOString()}),detail:async()=>({status:'completed',completedAt:new Date(now).toISOString()})},billing=new BillingService(join(dir,'billing.json'),{users,client,mailer,credentialGenerator:()=>generated,now:()=>now});await billing.load();const made=await billing.createPublic({email:user.email,phone:'08123456789',user}),first=await billing.statusPublic(made.order.orderCode,made.checkoutToken,{force:true});assert.equal(first.order.status,'paid');assert.equal(first.order.credentialDeliveryStatus,'pending');assert.equal(users.verifyPassword(user,oldPassword),true);assert.equal(users.verifyPassword(user,generated.password),false);now+=60001;const retried=await billing.statusPublic(made.order.orderCode,made.checkoutToken,{force:true});assert.equal(retried.order.credentialDeliveryStatus,'sent');assert.equal(users.verifyPassword(user,oldPassword),false);assert.equal(users.verifyPassword(user,generated.password),true);assert.equal(attempts,2);const disk=await readFile(join(dir,'billing.json'),'utf8');for(const raw of Object.values(generated))assert.equal(disk.includes(raw),false);await billing.close();
});

test('billing HTTP routes require the owning user session and reactivate an expired account',async t=>{
  const stateDir=await mkdtemp(join(tmpdir(),'gen-billing-http-')),now=Date.parse('2025-06-10T08:00:00.000Z'),password='user-password-long';const client={configured:true,create:async({orderId,amount})=>({project:'gen',orderId,amount,fee:0,totalPayment:amount,paymentMethod:'qris',paymentNumber:'000201010212',expiredAt:new Date(now+1200000).toISOString()}),detail:async()=>({status:'completed',completedAt:new Date(now).toISOString()})};const app=await createApp({stateDir,now:()=>now,pakasirClient:client});await new Promise(resolve=>app.server.listen(0,'127.0.0.1',resolve));t.after(()=>app.close());const base=`http://127.0.0.1:${app.server.address().port}`,post=(path,body,headers={})=>fetch(base+path,{method:'POST',headers:{'content-type':'application/json',...headers},...(body===undefined?{}:{body:JSON.stringify(body)})});
  assert.deepEqual(await (await fetch(base+'/billing/plan')).json(),{provider:'pakasir',configured:true,publicCheckoutConfigured:false,priceIdr:35000,durationMonths:1,rpmLimit:60,workerLimit:5});assert.equal((await post('/billing/order')).status,401);
  const user=await app.users.createTrial({email:'user@example.test',passwordVerifier:passwordVerifier(password),now:now-4*24*60*60*1000});let response=await post('/auth/login',{email:user.email,credential:password}),session=await response.json();assert.equal(session.entitlement,'profile-only');const cookie=response.headers.get('set-cookie');response=await post('/billing/order',undefined,{cookie});assert.equal(response.status,201);const order=await response.json();assert.equal((await fetch(base+'/billing/order',{headers:{cookie}})).status,200);response=await fetch(`${base}/billing/order/${order.orderCode}`,{headers:{cookie}});const paid=await response.json();assert.equal(paid.status,'paid');assert.equal(app.users.get(user.id).expiresAt,'2025-07-10T08:00:00.000Z');assert.equal((await (await fetch(base+'/auth/session',{headers:{cookie}})).json()).entitlement,'full');await app.users.update(user.id,{expiresAt:'2025-06-01T00:00:00.000Z'});assert.equal((await (await fetch(base+'/auth/session',{headers:{cookie}})).json()).entitlement,'profile-only');assert.equal((await post('/billing/order',undefined,{cookie})).status,201);
});

test('public order HTTP flow needs only email and phone, emails access, accumulates expiry, and revokes old sessions',async t=>{
  const stateDir=await mkdtemp(join(tmpdir(),'gen-public-http-')),now=Date.parse('2025-06-10T08:00:00.000Z'),generated=[{password:'first-random-password-long'},{password:'second-random-password-long'}],sent=[];let creates=0,credentialIndex=0;const mailer={sendTrialOtp:async()=>({sent:true}),sendPaidAccess:async value=>{sent.push(value);return{sent:true}}},client={configured:true,create:async({orderId,amount})=>{creates++;return{project:'gen',orderId,amount,fee:0,totalPayment:amount,paymentMethod:'qris',paymentNumber:'000201010212',expiredAt:new Date(now+1200000).toISOString()}},detail:async()=>({status:'completed',completedAt:new Date(now).toISOString()})};const app=await createApp({stateDir,now:()=>now,pakasirClient:client,mailer,trialLedgerSecret:'0123456789abcdef0123456789abcdef',billingCredentialGenerator:()=>generated[credentialIndex++]});await new Promise(resolve=>app.server.listen(0,'127.0.0.1',resolve));t.after(()=>app.close());const base=`http://127.0.0.1:${app.server.address().port}`,order=body=>fetch(base+'/billing/public/order',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),login=credential=>fetch(base+'/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:'buyer@example.test',credential})}),valid={email:'buyer@example.test',phone:'0812-3456-789'};
  assert.equal((await order({...valid,phone:'123'})).status,400);assert.equal((await order({...valid,password:'must-not-be-accepted'})).status,400);assert.equal((await (await fetch(base+'/billing/plan')).json()).publicCheckoutConfigured,true);let response=await order(valid);assert.equal(response.status,201);let value=await response.json(),checkout=response.headers.get('set-cookie').match(/checkout_session=[^;]+/)[0];assert.equal(value.accountAction,'new');assert.equal((await fetch(`${base}/billing/public/order/${value.orderCode}`,{headers:{cookie:'checkout_session=wrong'}})).status,401);response=await fetch(`${base}/billing/public/order/${value.orderCode}`,{headers:{cookie:checkout}});value=await response.json();assert.equal(value.status,'paid');assert.equal(value.credentialDeliveryStatus,'sent');assert.equal(value.authenticated,undefined);assert.equal(response.headers.get('set-cookie')?.includes('dashboard_session'),false);const user=app.users.findByEmail(valid.email);assert.equal(user.phone,'+628123456789');assert.equal(user.expiresAt,'2025-07-10T08:00:00.000Z');assert.equal(app.users.verifyPassword(user,generated[0].password),true);assert.equal(sent.length,1);assert.equal('otp' in sent[0],false);
  response=await login(generated[0].password);assert.equal(response.status,200);const oldSession=response.headers.get('set-cookie');response=await order(valid);assert.equal(response.status,201);value=await response.json();checkout=response.headers.get('set-cookie').match(/checkout_session=[^;]+/)[0];assert.equal(value.accountAction,'extend');assert.equal(app.users.verifyPassword(user,generated[0].password),true);assert.equal((await fetch(base+'/auth/session',{headers:{cookie:oldSession}})).status,200);response=await fetch(`${base}/billing/public/order/${value.orderCode}`,{headers:{cookie:checkout}});value=await response.json();assert.equal(value.credentialDeliveryStatus,'sent');assert.equal(app.users.get(user.id).expiresAt,'2025-08-10T08:00:00.000Z');assert.equal(app.users.verifyPassword(user,generated[0].password),false);assert.equal(app.users.verifyPassword(user,generated[1].password),true);assert.equal((await fetch(base+'/auth/session',{headers:{cookie:oldSession}})).status,401);assert.equal((await login(generated[0].password)).status,401);assert.equal((await login(generated[1].password)).status,200);assert.equal(sent.length,2);assert.equal(creates,2);const disk=await readFile(join(stateDir,'billing.json'),'utf8');for(const item of generated)for(const raw of Object.values(item))assert.equal(disk.includes(raw),false);
});
