import test from 'node:test';import assert from 'node:assert/strict';import {createMailer} from '../lib/mailer.js';
const config={SMTP_HOST:'smtp.test',SMTP_PORT:'465',SMTP_SECURE:'true',SMTP_USER:'u',SMTP_PASS:'p',SMTP_FROM_EMAIL:'trial@example.test',SMTP_FROM_NAME:'Gen Console'};
test('parses transport and returns only safe metadata',async()=>{let options,message;const mailer=createMailer(config,{createTransport:o=>(options=o,{sendMail:async m=>(message=m,{messageId:'id',accepted:[m.to],response:'250'})})});const result=await mailer.sendTrialOtp({to:'a@b.test',otp:'123456',expiresMinutes:10});assert.equal(options.port,465);assert.equal(options.secure,true);assert.match(message.text,/123456/);assert.deepEqual(result,{sent:true,messageId:'id'});assert.doesNotMatch(JSON.stringify(result),/a@b|250/);});
test('paid access email contains the generated password, expiry and order reference without OTP',async()=>{let message;const mailer=createMailer(config,{transport:{sendMail:async m=>(message=m,{messageId:'paid-id'})}}),result=await mailer.sendPaidAccess({to:'buyer@example.test',password:'random-paid-password-long',orderCode:'GEN-ORDER-1234',newExpiresAt:'2025-07-10T08:00:00.000Z'});assert.deepEqual(result,{sent:true,messageId:'paid-id'});assert.equal(message.subject,'Akses Gen Console Anda');for(const value of ['buyer@example.test','random-paid-password-long','GEN-ORDER-1234','Spam'])assert.match(message.text,new RegExp(value));assert.doesNotMatch(`${message.text}${message.html}`,/OTP/);});
test('paid access HTML escapes an address that contains markup-significant characters',async()=>{let message;const mailer=createMailer(config,{transport:{sendMail:async value=>(message=value,{})}});await mailer.sendPaidAccess({to:'buyer&tag@example.test',password:'random-paid-password-long',orderCode:'GEN-ORDER-1234',newExpiresAt:'2025-07-10T08:00:00.000Z'});assert.match(message.html,/buyer&amp;tag@example\.test/);assert.doesNotMatch(message.html,/buyer&tag@example\.test/);});
test('paid access email validates every security-sensitive field before sending',async()=>{let calls=0;const mailer=createMailer(config,{transport:{sendMail(){calls++;}}}),valid={to:'buyer@example.test',password:'random-paid-password-long',orderCode:'GEN-ORDER-1234',newExpiresAt:'2025-07-10T08:00:00.000Z'};for(const patch of [{password:'short'},{password:'unsafe password'},{orderCode:'bad code'},{newExpiresAt:'invalid'}])await assert.rejects(mailer.sendPaidAccess({...valid,...patch}));assert.equal(calls,0);});
test('rejects injection, malformed/multiple addresses, bad OTP without transport call',async()=>{let calls=0;const m=createMailer(config,{transport:{sendMail(){calls++;}}});for(const to of ['a@b.test\r\nBcc:x@y.test','a@b.test,b@c.test','Name <a@b.test>','bad',' a@b.test'])await assert.rejects(m.sendTrialOtp({to,otp:'123456',expiresMinutes:10}),/to/);for(const otp of ['12345','1234567','abcdef','12\n456'])await assert.rejects(m.sendTrialOtp({to:'a@b.test',otp,expiresMinutes:10}),/otp/);assert.equal(calls,0);});
test('rejects unsafe sender fields and invalid configuration',()=>{for(const patch of [{SMTP_FROM_EMAIL:'a@b.test\nBcc:x@y.test'},{SMTP_FROM_EMAIL:'a@b.test,b@c.test'},{SMTP_FROM_NAME:'Good\r\nBcc: x@y.test'},{SMTP_PORT:'0'},{SMTP_SECURE:'yes'}])assert.throws(()=>createMailer({...config,...patch},{transport:{sendMail(){}}}));});
test('does not log',async()=>{let calls=0;const old=console.log;console.log=()=>calls++;try{await createMailer(config,{transport:{sendMail:async()=>({})}}).sendTrialOtp({to:'a@b.test',otp:'123456',expiresMinutes:10});}finally{console.log=old;}assert.equal(calls,0);});
