import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,readFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {TrialStore,OTP_TTL_MS,RESEND_COOLDOWN_MS} from '../lib/trial.js';
const secret='s'.repeat(32), verifier={passwordSalt:'salt',passwordHash:'ab'.repeat(32)};
async function fixture(extra={}){const dir=await mkdtemp(join(tmpdir(),'trial-'));let now=1800000000000;const otps=['012345','111111','222222','333333','444444','555555'];const store=new TrialStore(join(dir,'trials.json'),{ledgerSecret:secret,now:()=>now,otpGenerator:()=>otps.shift(),...extra});await store.load();return{store,file:join(dir,'trials.json'),tick:n=>now+=n,now:()=>now};}
test('requires strong secret and load before mutation / only once',async()=>{assert.throws(()=>new TrialStore('x',{ledgerSecret:'short'}));const s=new TrialStore('x',{ledgerSecret:secret});assert.throws(()=>s.reserveSend('a@b.test',verifier),/loaded/);await s.load();await assert.rejects(s.load(),/initialized/);});
test('send reservation preserves prior pending and quota until commit; abort preserves it',async()=>{const{store,file,tick}=await fixture();const a=await store.reserveSend('a@b.test',verifier);assert.equal(await store.getPending('a@b.test'),null);await assert.rejects(store.reserveSend('a@b.test',verifier),{code:'SEND_IN_PROGRESS'});await store.abortSend(a.reservationId);const b=await store.reserveSend('a@b.test',verifier);await store.commitSend(b.reservationId);assert.ok(!await readFile(file,'utf8').then(x=>x.includes(b.otp)));const old=await store.getPending('a@b.test');tick(RESEND_COOLDOWN_MS);const c=await store.reserveSend('a@b.test',verifier);assert.deepEqual(await store.getPending('a@b.test'),old);await store.abortSend(c.reservationId);assert.deepEqual(await store.getPending('a@b.test'),old);});
test('validates exact password verifier schema',async()=>{const{store}=await fixture();for(const bad of [{}, {passwordSalt:'x',passwordHash:'zz'.repeat(32)}, {...verifier,password:'plain'}])await assert.rejects(store.reserveSend('a@b.test',bad),/passwordVerifier/);});
test('wrong attempts persist; correct activation is reserved and abortable',async()=>{const{store,now}=await fixture();const send=await store.reserveSend('a@b.test',verifier);await store.commitSend(send.reservationId);assert.equal((await store.beginVerification('a@b.test','999999')).reason,'invalid');const good=await store.beginVerification('a@b.test',send.otp);assert.deepEqual(good.passwordVerifier,verifier);await assert.rejects(store.beginVerification('a@b.test',send.otp),{code:'ACTIVATION_IN_PROGRESS'});await store.abortActivation(good.reservationId);assert.ok(await store.getPending('a@b.test'));const again=await store.beginVerification('a@b.test',send.otp);await store.commitActivation(again.reservationId,{userId:'u1',verifiedAt:now()});assert.equal(await store.hasConsumed('a@b.test'),true);assert.equal(await store.getPending('a@b.test'),null);});
test('expiry is inclusive and snapshot restores post-persist compensation',async()=>{const{store,tick,now}=await fixture();const s=await store.reserveSend('a@b.test',verifier);await store.commitSend(s.reservationId);tick(OTP_TTL_MS);assert.equal((await store.beginVerification('a@b.test',s.otp)).reason,'expired');const b=await store.reserveSend('b@b.test',verifier);await store.commitSend(b.reservationId);const snap=await store.snapshot();const a=await store.beginVerification('b@b.test',b.otp);await store.commitActivation(a.reservationId,{userId:'u',verifiedAt:now()});await store.restore(snap);assert.equal(await store.hasConsumed('b@b.test'),false);assert.ok(await store.getPending('b@b.test'));});
test('injected persist failure rolls back committed data',async()=>{let fail=false;const{store}=await fixture({persist:async()=>{if(fail)throw new Error('disk');}});const r=await store.reserveSend('a@b.test',verifier);fail=true;await assert.rejects(store.commitSend(r.reservationId),/disk/);assert.equal(await store.getPending('a@b.test'),null);});
