import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import {mkdtemp,readFile,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {scryptSync} from 'node:crypto';
import {createApp} from '../server.js';
import {TrialStore,OTP_TTL_MS,RESEND_COOLDOWN_MS,SEND_WINDOW_MS,PENDING_RETENTION_MS} from '../lib/trial.js';

const secret='trial integration secret '.repeat(2), adminPassword='administrator password', salt='admin-salt', hash=scryptSync(adminPassword,salt,32).toString('hex');
const json=(body,headers={})=>({method:'POST',headers:{'content-type':'application/json',...headers},body:JSON.stringify(body)});
async function fixture(extra={}){const stateDir=await mkdtemp(join(tmpdir(),'trial-http-'));let now=extra.startNow??1_800_000_000_000;const sent=[];const mailer=extra.mailer??{sendTrialOtp:async value=>sent.push(value)};const trial=extra.noTrial?undefined:new TrialStore(join(stateDir,'trial.json'),{ledgerSecret:secret,now:()=>now,otpGenerator:()=> '123456'});const app=await createApp({stateDir,adminEmail:'admin@example.com',adminPasswordSalt:salt,adminPasswordHash:hash,now:()=>now,trialRequestMinResponseMs:0,trialRequestAttemptLimit:1000,trialVerifyAttemptLimit:1000,...(!extra.noTrial?{trialStore:trial,mailer}:{}),...extra.options});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${app.server.address().port}`;return{app,stateDir,sent,request:(p,o={})=>fetch(base+p,o),tick:n=>now+=n,now:()=>now};}
async function restart(f,options={}){await f.app.close();const trial=new TrialStore(join(f.stateDir,'trial.json'),{ledgerSecret:secret,now:f.now,otpGenerator:()=> '123456'}),app=await createApp({stateDir:f.stateDir,adminEmail:'admin@example.com',adminPasswordSalt:salt,adminPasswordHash:hash,now:f.now,trialStore:trial,mailer:{sendTrialOtp:async value=>f.sent.push(value)},...options});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));f.app=app;const base=`http://127.0.0.1:${app.server.address().port}`;f.request=(p,o={})=>fetch(base+p,o);return f}
async function signup(f,email='person@any-domain.example',password='0123456789'){const r=await f.request('/auth/trial/request',json({email,password,confirmPassword:password}));return r}
async function verify(f,email='person@any-domain.example',otp='123456'){return f.request('/auth/trial/verify',json({email,otp}))}
async function adminToken(f){return (await (await f.request('/admin/login',json({email:'admin@example.com',password:adminPassword}))).json()).token}
const bearer=t=>({authorization:`Bearer ${t}`});

test('trial request exact validation accepts every valid domain and stores no secrets',async t=>{const f=await fixture();t.after(()=>f.app.close());for(const body of [{email:'a@b.test',password:'0123456789',confirmPassword:'0123456789',x:1},{email:'bad',password:'0123456789',confirmPassword:'0123456789'},{email:'a@b.test',password:'short',confirmPassword:'short'},{email:'a@b.test',password:'x'.repeat(1025),confirmPassword:'x'.repeat(1025)},{email:'a@b.test',password:'0123456789',confirmPassword:'different'}])assert.equal((await f.request('/auth/trial/request',json(body))).status,400);assert.equal((await signup(f)).status,202);assert.equal(f.sent[0].to,'person@any-domain.example');const disk=await readFile(join(f.stateDir,'trial.json'),'utf8');for(const secretValue of ['person@any-domain.example','0123456789','123456'])assert.equal(disk.includes(secretValue),false)});

test('generic enumeration and failed delivery preserve old OTP and send quota',async t=>{const f=await fixture();t.after(()=>f.app.close());await signup(f);f.tick(RESEND_COOLDOWN_MS);const old=await f.app.trial.getPending('person@any-domain.example'),send=f.app.trial.reserveSend.bind(f.app.trial);f.app.trial.reserveSend=async(...a)=>{const r=await send(...a);f.app.trial.reserveSend=send;throw Object.assign(new Error('smtp'),{reservation:r})};assert.equal((await signup(f)).status,202);assert.deepEqual(await f.app.trial.getPending('person@any-domain.example'),old);const admin=await adminToken(f);await f.request('/admin/users',json({email:'existing@example.com'},bearer(admin)));assert.equal((await signup(f,'existing@example.com')).status,202);assert.equal(f.sent.length,1)});

test('real mailer failure is indistinguishable, aborts reservation, and charges neither cooldown nor quota',async t=>{let fail=true;const delivered=[],f=await fixture({mailer:{sendTrialOtp:async value=>{if(fail)throw new Error('smtp down');delivered.push(value)}}});t.after(()=>f.app.close());const first=await signup(f),body=await first.text();assert.equal(first.status,202);assert.equal(delivered.length,0);assert.equal(await f.app.trial.getPending('person@any-domain.example'),null);fail=false;const retry=await signup(f);assert.equal(retry.status,202);assert.equal(await retry.text(),body);assert.equal(delivered.length,1);const old=await f.app.trial.getPending('person@any-domain.example');f.tick(RESEND_COOLDOWN_MS);fail=true;assert.equal((await signup(f)).status,202);assert.deepEqual(await f.app.trial.getPending('person@any-domain.example'),old);fail=false;assert.equal((await signup(f)).status,202);assert.equal(delivered.length,2)});

test('IP send cap persists for five successful sends per rolling hour',async t=>{const f=await fixture();t.after(()=>f.app.close());for(let i=0;i<5;i++)assert.equal((await signup(f,`ip-${i}@example.test`)).status,202);assert.equal(f.sent.length,5);await restart(f);assert.equal((await signup(f,'sixth@example.test')).status,202);assert.equal(f.sent.length,5);f.tick(SEND_WINDOW_MS+1);assert.equal((await signup(f,'after-window@example.test')).status,202);assert.equal(f.sent.length,6)});

test('verify is generic on bad states, limits attempts, and atomically creates exact 72h trial/session/ledger',async t=>{const f=await fixture();t.after(()=>f.app.close());assert.deepEqual(await (await verify(f,'missing@example.com')).json(),{error:'Invalid or expired code'});await signup(f);for(let i=0;i<5;i++)assert.equal((await verify(f,'person@any-domain.example','999999')).status,400);assert.equal((await verify(f)).status,400);f.tick(RESEND_COOLDOWN_MS);await signup(f,'second@example.com');const stamp=f.now(),r=await verify(f,'second@example.com');assert.equal(r.status,201);assert.match(r.headers.get('set-cookie'),/HttpOnly.*Secure.*SameSite=Lax/);const value=await r.json();assert.equal(JSON.stringify(value).includes('password'),false);assert.equal(JSON.stringify(value).includes('123456'),false);const u=f.app.users.findByEmail('second@example.com');assert.equal(u.accountType,'trial');assert.equal(u.trialStartedAt,new Date(stamp).toISOString());assert.equal(u.trialEndsAt,new Date(stamp+72*60*60*1000).toISOString());assert.equal(u.expiresAt,u.trialEndsAt);assert.equal(await f.app.trial.hasConsumed(u.email),true);assert.equal((await f.request('/auth/session',{headers:{cookie:r.headers.get('set-cookie')}})).status,200)});

test('one trial forever after hard delete, while admin may recreate managed',async t=>{const f=await fixture();t.after(()=>f.app.close());await signup(f);const activated=await verify(f),u=f.app.users.findByEmail('person@any-domain.example'),token=await adminToken(f);assert.equal(activated.status,201);assert.equal((await f.request(`/admin/users/${u.id}`,{method:'DELETE',headers:bearer(token)})).status,204);assert.equal((await signup(f)).status,202);assert.equal(f.sent.length,1);const made=await f.request('/admin/users',json({email:'person@any-domain.example'},bearer(token)));assert.equal(made.status,201);assert.equal((await made.json()).user.accountType,'managed')});

test('concurrent verify creates exactly one user and session',async t=>{const f=await fixture();t.after(()=>f.app.close());await signup(f);const rs=await Promise.all([verify(f),verify(f)]);assert.equal(rs.filter(r=>r.status===201).length,1);assert.equal(f.app.users.records.filter(u=>u.email==='person@any-domain.example').length,1);assert.equal(f.app.dashboard.sessions.filter(s=>s.role==='user').length,1)});

test('expired trial remains profile-only but cannot AI/MCP/key-create; extension restores full',async t=>{const f=await fixture({options:{dashboardSessionTtlMs:96*60*60*1000}});t.after(()=>f.app.close());await signup(f);let r=await verify(f),cookie=r.headers.get('set-cookie'),u=f.app.users.findByEmail('person@any-domain.example');r=await f.request('/profile/api-key',{method:'POST',headers:{cookie}});const key=(await r.json()).key;f.tick(72*60*60*1000);assert.equal((await f.request('/auth/session',{headers:{cookie}})).status,200);const profile=await (await f.request('/profile',{headers:{cookie}})).json();assert.equal(profile.remainingMs,0);assert.equal((await f.request('/profile/api-key',{method:'POST',headers:{cookie}})).status,403);assert.equal((await f.request('/dashboard/v1/status',{headers:{cookie}})).status,403);assert.equal((await f.request('/mcp',{method:'POST',headers:{authorization:`Bearer ${key}`},body:'{}'})).status,401);assert.equal((await f.request('/profile/api-key',{method:'DELETE',headers:{cookie}})).status,204);const a=await adminToken(f);await f.request(`/admin/users/${u.id}`,{...json({expiresAt:new Date(f.now()+10000).toISOString()},bearer(a)),method:'PATCH'});assert.equal((await (await f.request('/auth/session',{headers:{cookie}})).json()).entitlement,'full')});

test('login entitlement matrix and expired trial password rotation',async t=>{const f=await fixture({options:{dashboardSessionTtlMs:96*60*60*1000}});t.after(()=>f.app.close());await signup(f);const activated=await verify(f),oldCookie=activated.headers.get('set-cookie'),trial=f.app.users.findByEmail('person@any-domain.example'),admin=await adminToken(f);await f.request(`/admin/users/${trial.id}`,{...json({maxSessions:3},bearer(admin)),method:'PATCH'});f.tick(72*60*60*1000);let r=await f.request('/auth/login',json({email:trial.email,credential:'0123456789'}));assert.equal(r.status,200);assert.equal((await r.json()).entitlement,'profile-only');const expiredCookie=r.headers.get('set-cookie');r=await f.request('/profile/password',json({currentPassword:'0123456789',newPassword:'abcdefghij',confirmPassword:'abcdefghij'},{cookie:expiredCookie}));assert.equal(r.status,200);const newCookie=r.headers.get('set-cookie');assert.equal((await f.request('/auth/session',{headers:{cookie:oldCookie}})).status,401);assert.equal((await f.request('/auth/session',{headers:{cookie:expiredCookie}})).status,401);assert.equal((await f.request('/auth/session',{headers:{cookie:newCookie}})).status,200);const a=await adminToken(f),make=async(email,value={})=>(await (await f.request('/admin/users',json({email,...value},bearer(a)))).json()).user,login=async(email,credential)=>f.request('/auth/login',json({email,credential}));let u=await make('disabled@example.test',{active:false});assert.equal((await login(u.email,'wrong')).status,401);u=await make('expired-managed@example.test',{expiresAt:new Date(f.now()-1).toISOString()});assert.equal((await login(u.email,'wrong')).status,401);const active=await f.request('/admin/users',json({email:'active-managed@example.test'},bearer(a))),activeBody=await active.json();r=await login(activeBody.user.email,activeBody.password);assert.equal((await r.json()).entitlement,'full');await f.request(`/admin/users/${activeBody.user.id}`,{method:'DELETE',headers:bearer(a)});assert.equal((await login(activeBody.user.email,activeBody.password)).status,401);await f.request(`/admin/users/${trial.id}`,{...json({expiresAt:new Date(f.now()+1000).toISOString()},bearer(a)),method:'PATCH'});r=await login(trial.email,'abcdefghij');assert.equal((await r.json()).entitlement,'full')});

test('activation persistence faults roll back on disk and leave OTP retryable after restart',async()=>{for(const point of ['users.createTrial','trial.commitActivation','dashboard.create']){const email=`${point.replace(/\W/g,'-')}@example.test`,f=await fixture();try{assert.equal((await signup(f,email)).status,202,point);assert.ok(await f.app.trial.getPending(email),point);
    if(point==='users.createTrial'){const original=f.app.users.persist;let injected=false;f.app.users.persist=async(...args)=>{await original(...args);if(!injected){injected=true;throw new Error('users persist-then-throw')}}}
    else if(point==='trial.commitActivation'){const originalCommit=f.app.trial.commitActivation.bind(f.app.trial),originalPersist=f.app.trial.persist.bind(f.app.trial);f.app.trial.commitActivation=async(...args)=>{let injected=false;f.app.trial.persist=async(...persistArgs)=>{await originalPersist(...persistArgs);if(!injected){injected=true;throw new Error('trial persist-then-throw')}};try{return await originalCommit(...args)}finally{f.app.trial.persist=originalPersist}}}
    else{const original=f.app.dashboard.create.bind(f.app.dashboard);let injected=false;f.app.dashboard.create=async(...args)=>{const token=await original(...args);if(!injected){injected=true;throw new Error('dashboard persist-then-throw')}return token}}
    assert.equal((await verify(f,email)).status,500,point);await f.app.close();await restart(f);assert.equal(f.app.users.findByEmail(email),null,point);assert.equal(f.app.dashboard.sessions.filter(s=>s.role==='user').length,0,point);assert.equal(await f.app.trial.hasConsumed(email),false,point);assert.ok(await f.app.trial.getPending(email),point);assert.equal((await verify(f,email)).status,201,point)
  }finally{await f.app.close()}}});

test('startup activation journal recovers partial persisted activation and removes journal',async()=>{const email='journal-recovery@example.test',f=await fixture();try{assert.equal((await signup(f,email)).status,202);const begun=await f.app.trial.beginVerification(email,'123456'),users=f.app.users.snapshot(),trial=await f.app.trial.snapshot(),dashboard=f.app.dashboard.snapshot(),stamp=f.now(),user=await f.app.users.createTrial({email,label:'journal',passwordVerifier:begun.passwordVerifier,now:stamp});await f.app.trial.commitActivation(begun.reservationId,{userId:user.id,verifiedAt:stamp});await f.app.dashboard.create({role:'user',userId:user.id});await writeFile(join(f.stateDir,'activation-journal.json'),JSON.stringify({version:1,users,trial,dashboard}));await restart(f);assert.equal(f.app.users.findByEmail(email),null);assert.equal(await f.app.trial.hasConsumed(email),false);assert.ok(await f.app.trial.getPending(email));assert.equal(f.app.dashboard.sessions.filter(s=>s.role==='user').length,0);await assert.rejects(readFile(join(f.stateDir,'activation-journal.json'),'utf8'),{code:'ENOENT'});assert.equal((await verify(f,email)).status,201)}finally{await f.app.close()}});

test('startup cleanup removes stale pending trials',async t=>{const f=await fixture();t.after(()=>f.app.close());await signup(f);assert.ok(await f.app.trial.getPending('person@any-domain.example'));f.tick(PENDING_RETENTION_MS+1);await restart(f);assert.equal(await f.app.trial.getPending('person@any-domain.example'),null)});

test('missing trial configuration affects trial endpoints only',async t=>{const f=await fixture({noTrial:true});t.after(()=>f.app.close());assert.equal((await signup(f)).status,503);assert.equal((await verify(f)).status,503);assert.equal((await f.request('/health')).status,200);assert.equal((await f.request('/admin/login',json({email:'admin@example.com',password:adminPassword}))).status,200)});

test('health reports trial readiness without degrading core health',async t=>{const ready=await fixture(),off=await fixture({noTrial:true});t.after(()=>Promise.all([ready.app.close(),off.app.close()]));assert.deepEqual(await (await ready.request('/health')).json(),{status:'ok',trial:'ready'});assert.deepEqual(await (await off.request('/health')).json(),{status:'ok',trial:'unavailable'})});

test('per-IP attempt limits charge before work and verify spans emails',async t=>{const f=await fixture({options:{trialRequestAttemptLimit:2,trialVerifyAttemptLimit:2}});t.after(()=>f.app.close());assert.equal((await signup(f,'one@example.test')).status,202);assert.equal((await signup(f,'two@example.test')).status,202);assert.equal((await signup(f,'three@example.test')).status,429);assert.equal(f.sent.length,2);assert.equal((await verify(f,'one@example.test','999999')).status,400);assert.equal((await verify(f,'two@example.test','999999')).status,400);const blocked=await verify(f,'unknown-third@example.test','999999');assert.equal(blocked.status,429);assert.equal(blocked.headers.has('retry-after'),true)});

test('valid-shape eligible and existing trial requests share minimum response floor and exact generic body',async t=>{const f=await fixture({options:{trialRequestMinResponseMs:40}});t.after(()=>f.app.close());const expected={accepted:true,message:'Jika memenuhi syarat, kode verifikasi telah dikirim.'};let start=Date.now(),r=await signup(f,'floor@example.test');assert.ok(Date.now()-start>=30);assert.deepEqual(await r.json(),expected);const admin=await adminToken(f);await f.request('/admin/users',json({email:'floor-existing@example.test'},bearer(admin)));start=Date.now();r=await signup(f,'floor-existing@example.test');assert.ok(Date.now()-start>=30);assert.deepEqual(await r.json(),expected)});

test('blocked mail send does not hold global mutation queue',async t=>{let release;const blocked=new Promise(r=>release=r),f=await fixture({mailer:{sendTrialOtp:()=>blocked}});t.after(()=>f.app.close());const pending=signup(f);await new Promise(r=>setTimeout(r,30));const started=Date.now();assert.equal((await f.request('/admin/login',json({email:'admin@example.com',password:adminPassword}))).status,200);assert.ok(Date.now()-started<300);release();assert.equal((await pending).status,202)});

test('stalled trial body remains outside mutation queue',async t=>{const f=await fixture({options:{bodyTimeoutMs:250}});t.after(()=>f.app.close());const port=f.app.server.address().port;let done;const response=new Promise(r=>done=r),req=http.request({host:'127.0.0.1',port,path:'/auth/trial/request',method:'POST',headers:{'content-type':'application/json','content-length':'200'}},res=>{res.resume();res.on('end',()=>done(res))});req.write('{"email":"stalled');assert.equal((await f.request('/admin/login',json({email:'admin@example.com',password:adminPassword}))).status,200);assert.equal((await response).statusCode,408);req.destroy()});
